sudo: required
language: c
script:
- export ntoolchainbranch="google_gcc"
- export ntoolchainchoice="1"
- git clone -b "${ntoolchainbranch}" "https://github.com/TeamVee/android_prebuilt_toolchains" "../android_prebuilt_toolchains"
- export nbasebuildsh="234${ntoolchainchoice}56q"
- source build.sh <<< "${nbasebuildsh}"
