language: c
script:
# Toolchain Choice
# This will clone TeamVee Prebuilt Toolchains in directory described in build.sh
#
# Branchs available is:
# Google Branch is "google_gcc" | (1) 4.7 / (2) 4.8
# Linaro Branch is "linaro_gcc" | (1) 4.8.4 / (2) 4.9.4

# Toolchain select here is Google 4.7
- export ntoolchainbranch="google_gcc"
- export ntoolchainchoice="1"
- git clone -b "${ntoolchainbranch}" "https://github.com/TeamVee/android_prebuilt_toolchains" "../android_prebuilt_toolchains"

# This will call build.sh with following parameters inside ${nbasebuildsh}:
#
# 'export nbasebuildsh="234${ntoolchainchoice}56q"'
# 'source build.sh <<< "${nbasebuildsh}"'
#
# First "2" is "Clean Kernel"
# Second "3" is "Device Choice to Xperia E1"
# Fourth "4" is "Toolchain Choice"
# ${ntoolchainchoice} is "Number of Toolchain under Toolchain Choice"
# Sixth "5" is "Build Kernel"
# Seventh "6" is "Zip the kernel and Modules"
# Last "q" is to Exit of Script

# For Sony Xperia E1
- export nbasebuildsh="234${ntoolchainchoice}56q"
- source build.sh <<< "${nbasebuildsh}"
branches:
  except:
    - stock
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "cZH5KE3ZsOX63BUq/iqaPtGoUHInQHtEz7+wxptKp/1DyZf2gJ6y7tBWRdkJ/3jnW/qZlcDWTJrpSBkgUWiJys9JodefAqKuHelxxUPppZuaYY2ZAmm43kJpVKcK01xkl/8anRBIUGwXgReX/nW6AbKgmR2LoC6fW8u5Yd8WMv62WVzNRHqPbWwC+mRsi+kBHXSLPy0Z4eToTBjeWHQA54zzzrYRU1oxQIxSW/S+Sz6tqxpofvs5hE51YjIW41of2Pyqrm+Hp5Z1V+pOrfho1zq9fmjEcUXDAHTiEwilpF6IskjKnQrPjOS6+4zf15C2L/EELhVr7isgDc+JEHmZqDzr0Txe/d3dtJiFkej/efLfksXDqb38nQkEleP0oREGzJ/BXe8xzfv2nOIB0Ty9JFGgzfXvVYfPHJF7rTlaI+4XvrqNxziHetNWPlYiIgSsfIJ2Vijy+iJ5UQnt6P7SQoPiSvMESnhFxxpLgvY5NoV/KSqj29vWP1O04TgiifQdX+051Xs0w3CXVGGipQH8K/ucAwkB1Mo8jHcnFb3gp45e5yPs36wu6q0B+GF2aX3gnVijOxGIUdt2NvqGyfXL6MMYvCUoQg0mHjsF5o96QvTtNdc4Xc9YGXNnBT2i9GvyqNYumLV/LIHmKCHAzt/QWhFheQJHpnqdqEw8b0fWgDk="
  file: "zip-creator/${zipfile}"
  on:
    tags: true
